//! `TestApp` factory: builds a fresh DB pool, applies migrations,
//! constructs `AppState`, and wraps it in an `axum_test::TestServer`
//! with cookies enabled.
//!
//! Each test gets its own pool. The pool is backed by a temp-file
//! SQLite database (rather than `sqlite::memory:`) because sqlx's
//! pool keeps multiple connections, and an in-memory database
//! gives each connection its own private memory space — making
//! the second connection see an empty DB. A temp file gives a
//! shared backing store, and SQLite's WAL mode keeps it well-
//! behaved for the test's lifetime.
//!
//! Temp directories are allocated by `tempfile::TempDir`
//! (`QA-001`, baseline `§10.13`). An earlier version named the
//! directory from `SystemTime::now().as_nanos()` alone; two tests
//! entering `spawn` within the same clock tick got the same
//! directory and the same `test.db`, and `create_dir_all` succeeds
//! on an existing directory, so nothing signalled the collision —
//! the second arrival just failed against a database mid-migration
//! or already locked. `tempfile` guarantees a unique path by
//! construction (pid, a process-local atomic counter, and
//! randomness — not just the clock), and the `TempDir` handle held
//! on `TestApp` removes the directory on drop, closing the "these
//! accumulate under `/tmp` forever" half of the same finding.

use std::time::Duration;

use axum_test::TestServer;
use peisear_storage::{Pool, pool};
use peisear_web::{AppState, build_router};
use tempfile::TempDir;

/// A running test instance of the peisear application. Holds the
/// backing `TempDir` so the directory lives exactly as long as the
/// `TestApp` does and is removed when it drops.
pub struct TestApp {
    pub server: TestServer,
    pub db: Pool,
    _temp_dir: TempDir,
}

impl TestApp {
    /// Spin up a fresh test app with a unique DB file. Migrations
    /// are applied. The JWT secret is fixed for tests so tokens
    /// generated by helpers stay valid across the same test.
    pub async fn spawn() -> Self {
        let temp_dir = tempfile::Builder::new()
            .prefix("peisear-web-it-")
            .tempdir()
            .expect("create test temp dir");
        let url = format!("sqlite://{}/test.db", temp_dir.path().display());

        let db = pool::connect(&url)
            .await
            .unwrap_or_else(|e| panic!("connect test pool at {}: {e}", temp_dir.path().display()));
        pool::migrate(&db)
            .await
            .unwrap_or_else(|e| panic!("apply migrations at {}: {e}", temp_dir.path().display()));

        let state = AppState {
            db: db.clone(),
            jwt_secret: "test-jwt-secret-must-not-be-used-in-production".into(),
            // cookie_secure=false so the auth cookie is sent over
            // the test server's plain HTTP. Production sets this
            // to true via Config::from_env.
            cookie_secure: false,
        };

        let router = build_router(state);

        // Save cookies across requests so that calls after `login`
        // carry the auth cookie automatically.
        //
        // axum-test 20 exposes this via `TestServer::builder()`
        // returning a `TestServerBuilder` whose `.build(router)`
        // returns a `TestServer` directly (no fallible Result).
        // expect_success_by_default is OFF by default, which is
        // what we want — handlers legitimately return 4xx (auth,
        // 403, 409, validation) and the tests assert explicitly.
        let server = TestServer::builder().save_cookies().build(router);

        Self {
            server,
            db,
            _temp_dir: temp_dir,
        }
    }
}

/// Convenience for one-off tests.
pub async fn spawn() -> TestApp {
    TestApp::spawn().await
}

/// Sleep briefly so a subsequent write to the same row produces
/// a strictly-later `updated_at` timestamp. SQLite's
/// `CURRENT_TIMESTAMP` has whole-second precision, so without a
/// pause two writes in the same second would compare equal —
/// breaking optimistic-lock tests that rely on `updated_at` as
/// the version.
pub async fn ensure_distinct_timestamp() {
    tokio::time::sleep(Duration::from_millis(1100)).await;
}
